### ISSUE TITLE
Broken on Powercord with bdCpmpat

### ISSUE THREAD

**Issue by D3XX3R** [Juby210/EDPluginsLoader#1]
When I start the plugin I get the first error. When I try to open the ed plugin folder I get the second error.
![Image of Yaktocat](https://a.d3xx3r.de/​​‍‌‌​‌‌‌‌​​​​​‌‍‌‌‌)

**Comment by God-damnit-all** [comment]
I can confirm, I'm having this issue as well.

**Comment by Juby210** [comment]
```
(Plugin v0.0.7)
```
latest version is v0.0.8, just update plugin (by update plugin i mean update ed plugins loader)

**Comment by Juby210** [comment]
Ah, this issue also exists on latest. Anyway ED plugins folder is bdCompat's plugins folder. Just move ed plugins to bdCompat's plugins folder and them should work!

**Comment by D3XX3R** [comment]
What should the folder be called exactly? I've never used EnhancedDiscord.
Edit: After I read you message again I understood. Plugins work so I guess this issue can be closed.

**Comment by God-damnit-all** [comment]
> Ah, this issue also exists on latest. Anyway ED plugins folder is bdCompat's plugins folder. Just move ed plugins to bdCompat's plugins folder and them should work!

I'm on v0.0.8 and direct_download.js (one of the default ED plugins) doesn't work anymore.

**Comment by Juby210** [comment]
Direct download uses electron remote which is unsupported on powercord anymore. My recommendation is switching to [Lighty's SaveToRedux](https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/SaveToRedux) for BD.

**Comment by ImportTaste** [comment]
> Direct download uses electron remote which is unsupported on powercord anymore. My recommendation is switching to [Lighty's SaveToRedux](https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/SaveToRedux) for BD.

Seems to be broken now.
